# Generated by Django 6.0.3 on 2026-03-09 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Desafío')),
                ('description', models.TextField(verbose_name='Descripción del Reto / Necesidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(limit_choices_to={'role': 'DEMANDANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='published_challenges', to='corporate.organization')),
            ],
            options={
                'verbose_name': 'Desafío',
                'verbose_name_plural': 'Desafíos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField(verbose_name='Propuesta Tecnológica / Solución')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'role': 'OFERENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_proposals', to='corporate.organization')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='marketplace.challenge')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'unique_together': {('challenge', 'applicant')},
            },
        ),
    ]
