# Generated by Django 6.0.3 on 2026-03-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_rename_tax_id_and_translate_roles'),
        ('marketplace', '0002_translate_role_limit_choices'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('challenge', 'applicant'), name='unique_application_per_challenge_and_applicant'),
        ),
    ]
