# Generated by Django 6.0.3 on 2026-03-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='application_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de aplicación'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('CLOSED', 'Cerrado'), ('UNDER_EVALUATION', 'En evaluación'), ('AWARDED', 'Adjudicado'), ('ARCHIVED', 'Archivado')], default='PUBLISHED', max_length=24, verbose_name='Estado'),
        ),
    ]
