# Generated by Django 6.0.3 on 2026-03-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_challenge_application_deadline_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='capabilities_evidence',
            field=models.TextField(blank=True, default='', verbose_name='Capacidades y evidencia'),
        ),
        migrations.AddField(
            model_name='application',
            name='execution_plan',
            field=models.TextField(blank=True, default='', verbose_name='Plan de ejecución'),
        ),
        migrations.AddField(
            model_name='application',
            name='problem_understanding',
            field=models.TextField(blank=True, default='', verbose_name='Entendimiento del problema'),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_solution',
            field=models.TextField(blank=True, default='', verbose_name='Solución propuesta'),
        ),
        migrations.AlterField(
            model_name='application',
            name='proposal_text',
            field=models.TextField(blank=True, default='', verbose_name='Resumen legado de propuesta'),
        ),
    ]
