# Generated by Django 6.0.3 on 2026-03-20 01:56

import django.db.models.deletion
from django.db import migrations, models


def _parse_criteria(raw_criteria):
    return [
        line.lstrip("-*0123456789. ").strip()
        for line in (raw_criteria or "").splitlines()
        if line.strip()
    ]


def backfill_structured_evaluation_criteria(apps, schema_editor):
    Challenge = apps.get_model("marketplace", "Challenge")
    ChallengeEvaluationCriterion = apps.get_model(
        "marketplace",
        "ChallengeEvaluationCriterion",
    )

    criteria_to_create = []
    for challenge in Challenge.objects.exclude(evaluation_criteria=""):
        for position, label in enumerate(
            _parse_criteria(challenge.evaluation_criteria),
            start=1,
        ):
            criteria_to_create.append(
                ChallengeEvaluationCriterion(
                    challenge_id=challenge.pk,
                    label=label,
                    position=position,
                )
            )

    if criteria_to_create:
        ChallengeEvaluationCriterion.objects.bulk_create(criteria_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_challenge_evaluation_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeEvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Criterio')),
                ('position', models.PositiveIntegerField(verbose_name='Posición')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria_items', to='marketplace.challenge')),
            ],
            options={
                'verbose_name': 'Criterio de evaluación',
                'verbose_name_plural': 'Criterios de evaluación',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('challenge', 'position'), name='unique_evaluation_criterion_position_per_challenge')],
            },
        ),
        migrations.RunPython(
            backfill_structured_evaluation_criteria,
            migrations.RunPython.noop,
        ),
    ]
