# Generated by Django 6.0.3 on 2026-05-05 22:03

import apps.marketplace.content
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DEFAULT_CATEGORIES = (
    "Agrotech",
    "Salud",
    "Educación",
    "Energía",
    "Sostenibilidad",
    "Industria 4.0",
    "Logística",
    "Fintech",
    "Gobierno digital",
    "Inteligencia artificial",
)


def seed_initial_categories(apps, schema_editor):
    ChallengeCategory = apps.get_model('marketplace', 'ChallengeCategory')
    from django.utils.text import slugify

    for position, name in enumerate(DEFAULT_CATEGORIES, start=1):
        ChallengeCategory.objects.update_or_create(
            slug=slugify(name),
            defaults={
                'name': name,
                'position': position,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_application_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Categoría de desafío',
                'verbose_name_plural': 'Categorías de desafío',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opaque_id', models.CharField(default=apps.marketplace.content.new_opaque_id, editable=False, max_length=32, unique=True, verbose_name='Identificador opaco')),
                ('file', models.FileField(upload_to=apps.marketplace.content.build_attachment_upload_path, validators=[apps.marketplace.content.validate_attachment_file], verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('content_type', models.CharField(max_length=120, verbose_name='Tipo de contenido')),
                ('size', models.PositiveIntegerField(verbose_name='Tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketplace.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de propuesta',
                'verbose_name_plural': 'Adjuntos de propuesta',
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opaque_id', models.CharField(default=apps.marketplace.content.new_opaque_id, editable=False, max_length=32, unique=True, verbose_name='Identificador opaco')),
                ('file', models.FileField(upload_to=apps.marketplace.content.build_attachment_upload_path, validators=[apps.marketplace.content.validate_attachment_file], verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('content_type', models.CharField(max_length=120, verbose_name='Tipo de contenido')),
                ('size', models.PositiveIntegerField(verbose_name='Tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketplace.challenge')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de desafío',
                'verbose_name_plural': 'Adjuntos de desafío',
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='marketplace.challengecategory'),
        ),
        migrations.RunPython(seed_initial_categories, migrations.RunPython.noop),
    ]
