# Generated by Django 6.0.3 on 2026-07-23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0003_alter_organization_logo"),
        ("marketplace", "0009_challengecategory_applicationattachment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DRAFT_CREATED", "Borrador creado"),
                            ("DRAFT_UPDATED", "Borrador actualizado"),
                            ("PUBLISHED", "Desafío publicado"),
                            ("CLOSED", "Recepción cerrada"),
                            ("CANCELLED", "Desafío cancelado"),
                            ("DESERTED", "Desafío declarado desierto"),
                        ],
                        max_length=24,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        verbose_name="Estado anterior",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        max_length=24,
                        verbose_name="Estado resultante",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del evento",
                    ),
                ),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=False,
                        verbose_name="Transición automática",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de ciclo de vida del desafío",
                "verbose_name_plural": "Eventos de ciclo de vida del desafío",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="estimated_duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Duración estimada (días)",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="offer_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COP", "Peso colombiano (COP)"),
                    ("USD", "Dólar estadounidense (USD)"),
                    ("EUR", "Euro (EUR)"),
                ],
                default="",
                max_length=3,
                verbose_name="Moneda de la oferta",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="offered_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor total ofertado",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="budget_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text=(
                    "Los registros históricos pueden no tener presupuesto. "
                    "Toda nueva publicación debe definirlo."
                ),
                max_digits=18,
                null=True,
                verbose_name="Presupuesto máximo",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="budget_currency",
            field=models.CharField(
                choices=[
                    ("COP", "Peso colombiano (COP)"),
                    ("USD", "Dólar estadounidense (USD)"),
                    ("EUR", "Euro (EUR)"),
                ],
                default="COP",
                max_length=3,
                verbose_name="Moneda del presupuesto",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("PUBLISHED", "Publicado"),
                    ("CLOSED", "Cerrado"),
                    ("UNDER_EVALUATION", "En evaluación"),
                    ("AWARDED", "Adjudicado"),
                    ("CANCELLED", "Cancelado"),
                    ("DESERTED", "Desierto"),
                    ("ARCHIVED", "Archivado"),
                ],
                default="DRAFT",
                max_length=24,
                verbose_name="Estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("offered_amount__isnull", True),
                    ("offered_amount__gt", 0),
                    _connector="OR",
                ),
                name="application_offered_amount_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_duration_days__isnull", True),
                    ("estimated_duration_days__gt", 0),
                    _connector="OR",
                ),
                name="application_duration_days_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget_amount__isnull", True),
                    ("budget_amount__gt", 0),
                    _connector="OR",
                ),
                name="challenge_budget_amount_positive_or_null",
            ),
        ),
        migrations.AddField(
            model_name="challengelifecycleevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="challenge_lifecycle_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challengelifecycleevent",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lifecycle_events",
                to="marketplace.challenge",
            ),
        ),
    ]
