# Generated by Django 6.1.2 on 2026-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_alter_organization_logo'),
        ('marketplace', '0011_weighted_evaluation_criteria'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_at__isnull', True), ('status', 'DRAFT')), models.Q(('applied_at__isnull', False), ('status', 'SUBMITTED')), _connector='OR'), name='application_status_matches_submission_date'),
        ),
    ]
