# Generated by Django 6.0.3 on 2026-05-05 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_initial_titulars(apps, schema_editor):
    User = apps.get_model('identity', 'User')
    Organization = apps.get_model('corporate', 'Organization')
    for organization in Organization.objects.all():
        first_user = (
            User.objects.filter(organization=organization, is_active=True)
            .order_by('pk')
            .first()
        )
        if first_user is not None:
            first_user.is_organization_titular = True
            first_user.is_email_verified = True
            first_user.save(update_fields=['is_organization_titular', 'is_email_verified'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('corporate', '0003_alter_organization_logo'),
        ('identity', '0002_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=16, verbose_name='Estado')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de unión a organización',
                'verbose_name_plural': 'Solicitudes de unión a organización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_policy_version',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Versión de política aceptada'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_version',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Versión de términos aceptada'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Correo verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organization_titular',
            field=models.BooleanField(default=False, verbose_name='Representante titular'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('PENDING_APPROVAL', 'Pendiente de aprobación'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=24, verbose_name='Estado de cuenta'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_organization_titular', True), ('status', 'ACTIVE')), fields=('organization',), name='unique_active_titular_per_organization'),
        ),
        migrations.RunPython(assign_initial_titulars, migrations.RunPython.noop),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_organization_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='corporate.organization'),
        ),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organization', 'requester'), name='unique_pending_join_request_per_user_and_organization'),
        ),
    ]
