# Generated by Django 6.0.3 on 2026-07-23 17:55

import apps.identity.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0003_alter_organization_logo"),
        ("identity", "0004_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.identity.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="IdentityAuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            (
                                "REPRESENTATIVE_JOIN_REQUESTED",
                                "Solicitud de unión creada",
                            ),
                            (
                                "REPRESENTATIVE_JOIN_APPROVED",
                                "Solicitud de unión aprobada",
                            ),
                            (
                                "REPRESENTATIVE_JOIN_REJECTED",
                                "Solicitud de unión rechazada",
                            ),
                            (
                                "REPRESENTATIVE_JOIN_EXPIRED",
                                "Solicitud de unión expirada",
                            ),
                            (
                                "ORGANIZATION_OWNERSHIP_TRANSFERRED",
                                "Titularidad transferida",
                            ),
                        ],
                        max_length=40,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Snapshot",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(verbose_name="Fecha del evento"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identity_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "join_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="identity.organizationjoinrequest",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_audit_entries",
                        to="corporate.organization",
                    ),
                ),
                (
                    "secondary_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_identity_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identity_audit_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de auditoría de identidad",
                "verbose_name_plural": "Entradas de auditoría de identidad",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
