# Generated by Django 6.0.3 on 2026-03-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('business_name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('chamber_of_commerce_record', models.CharField(max_length=100, verbose_name='Registro Cámara de Comercio')),
                ('role', models.CharField(choices=[('DEMANDANTE', 'Demandante (Seeker)'), ('OFERENTE', 'Oferente (Provider)')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='corporate/logos/')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('economic_activity', models.TextField(blank=True, verbose_name='Actividad Económica')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Organización',
            },
        ),
    ]
