# Generated by Django 6.0.3 on 2026-03-20 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EVALUATION_STARTED', 'Evaluación iniciada'), ('CHALLENGE_AWARDED', 'Desafío adjudicado')], max_length=32, verbose_name='Tipo')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Mensaje')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='Enlace')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
