# Generated by Django 6.0.3 on 2026-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EVALUATION_STARTED", "Evaluación iniciada"),
                    ("APPLICATION_EVALUATED", "Propuesta evaluada"),
                    ("CHALLENGE_AWARDED", "Desafío adjudicado"),
                    (
                        "REPRESENTATIVE_JOIN_REQUESTED",
                        "Solicitud de unión creada",
                    ),
                    (
                        "REPRESENTATIVE_JOIN_APPROVED",
                        "Solicitud de unión aprobada",
                    ),
                    (
                        "REPRESENTATIVE_JOIN_REJECTED",
                        "Solicitud de unión rechazada",
                    ),
                    (
                        "REPRESENTATIVE_JOIN_EXPIRED",
                        "Solicitud de unión expirada",
                    ),
                    (
                        "ORGANIZATION_OWNERSHIP_TRANSFERRED",
                        "Titularidad transferida",
                    ),
                ],
                max_length=40,
                verbose_name="Tipo",
            ),
        ),
    ]
